name: Test
on:
  - push

jobs:
  test:
    strategy:
      matrix:
        go:
          - "1.20"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint install
        uses: golangci/golangci-lint-action@v3

      - name: Lint
        run: make lint
